// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPcz72ArLG7bmzZ50nKNTtG2Da_2RuJ-A',
    appId: '1:629739394819:android:706c0ef097e5b864d63b36',
    messagingSenderId: '629739394819',
    projectId: 'financly-9074c',
    storageBucket: 'financly-9074c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj4JkyR5MphSEevwirrW0aTxi4EInkoBU',
    appId: '1:629739394819:ios:7f69ab17c5c00679d63b36',
    messagingSenderId: '629739394819',
    projectId: 'financly-9074c',
    storageBucket: 'financly-9074c.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkftsSevA9eMlnr7RYAeRPUOcVgy2Tvxw',
    appId: '1:629739394819:web:9c2f96342b62167ad63b36',
    messagingSenderId: '629739394819',
    projectId: 'financly-9074c',
    authDomain: 'financly-9074c.firebaseapp.com',
    storageBucket: 'financly-9074c.firebasestorage.app',
    measurementId: 'G-KWL9XXDXX7',
  );

}